Repository wrappid/wrappid-module, pull requests merged in 2024-01, with the labels that each got.

#6 update wrappid module
  .eslint/app/.eslintrc.js
  .eslint/service/.eslintrc.js
  .eslintrc.js
  .github/pull_request_template.md
  .github/workflows/pr-guardrails.yml
  .husky/commit-msg
  .husky/pre-commit
  .vscode/settings.json
  commitlint.config.js
  lint-staged.config.js
  package-lock.json
  package.json
  service/controllers.registry.js
  service/controllers/test.controller.js
  service/functions.registry.js
  service/functions/test.functions.js
  service/middlewares.registry.js
  service/middlewares/test.middleware.js
  service/models.registry.js
  service/models/TestDatas.model.js
  service/tasks.registry.js
  service/tasks/TestTask.js
  service/validations.registry.js
Labels: enhancement

#9 docs: 🔒 license added
  LICENSE
Labels: documentation

#11 Update wrappid module template
  LICENSE
Labels: enhancement

#14 ci: local branch rules implementation and linting
  .eslint/app/.eslintrc.js
  .eslint/service/.eslintrc.js
  .eslintrc.js
  .github/workflows/pr-guardrails.yml
  lint-staged.config.js
  package-lock.json
  package.json
Labels: enhancement

#21 bug: pr-guardrails - removed files are included in lint files
  .github/workflows/pr-guardrails.yml
Labels: bug
