Repository wrappid/wrappid-module, pull requests merged in 2024-02, with the labels that each got.

#25 enhancement: wrappid styles related changes
  .vscode/settings.json
  app/styles/DefaultModuleStyles.js
  app/styles/LargeModuleStyles.js
  app/styles/MediumModuleStyles.js
  app/styles/SmallModuleStyles.js
  app/styles/XLargeModuleStyles.js
  app/styles/XXLargeModuleStyles.js
Labels: enhancement

#32 Merge development into main
  .github/workflows/auto-create-and-merge-pr.yml
  .husky/pre-commit
  ATTRIBUTIONS.md
  package-lock.json
  package.json
  scripts/attributions.gen.js
  service/controllers.registry.js
  service/controllers.registry.ts
  service/controllers/test.controller.ts
  service/functions.registry.js
  service/functions.registry.ts
  service/functions/test.functions.ts
  service/middlewares.registry.js
  service/middlewares.registry.ts
  service/middlewares/test.middleware.ts
  service/models.registry.js
  service/models.registry.ts
  service/models/TestDatas.model.js
  service/models/TestDatas.model.ts
  service/tasks.registry.js
  service/tasks.registry.ts
  service/tasks/TestTask.ts
  service/validations.registry.js
  service/validations.registry.ts
  service/validations/test.validation.ts
Labels: enhancement

#33 Revert "refactor: service folder move to typescript"
  package-lock.json
  package.json
  service/controllers.registry.js
  service/controllers.registry.ts
  service/controllers/test.controller.js
  service/functions.registry.js
  service/functions.registry.ts
  service/functions/test.functions.js
  service/middlewares.registry.js
  service/middlewares.registry.ts
  service/middlewares/test.middleware.js
  service/models.registry.js
  service/models.registry.ts
  service/models/TestDatas.model.js
  service/models/TestDatas.model.ts
  service/tasks.registry.js
  service/tasks.registry.ts
  service/tasks/TestTask.js
  service/validations.registry.js
  service/validations.registry.ts
  service/validations/test.validation.js
Labels: bug

#43 fix(core): :bugfix: ts compilation error
  service/middlewares/test.middleware.ts
Labels: bugfix

#46 refactor: :art: fix eslint
  .eslint/service/.eslintrc.js
  .eslintrc.js
  package-lock.json
  package.json
  service/controllers/test.controller.ts
  service/functions/test.functions.ts
  service/tasks/TestTask.ts
  service/validations/test.validation.ts
Labels: enhancement

#49 fix: configure ESLint to recognize the module path
  .eslint/service/.eslintrc.js
Labels: documentation

#51 bugfix(config): :wrench: update code style script pr-guardrails
  .github/workflows/pr-guardrails.yml
Labels: enhancement

#52 merge: development into main
  .github/workflows/pr-guardrails.yml
Labels: enhancement

#55 enhancement: pr guardrails and package.json dependencies.
  .github/workflows/pr-guardrails.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, dependencies
